name: Build and Run on Self-Hosted Runner

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build_and_run:
    runs-on: self-hosted  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install Dependencies
        run: npm install 

      - name: Build Application
        run: npm run build 

      - name: Run Application
        run: npm start  
